version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
      
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  webluis:
    build: .
    restart: always
    expose:
      - '85:80'
    environment:
      - VIRTUAL_HOST=luissalberto.com
      - LETSENCRYPT_HOST=luissalberto.com
      - LETSENCRYPT_EMAIL=diego@luissalberto.com
    volumes:
      - ./Luis:/usr/share/nginx/html
      
  webcrepas:
    build: .
    restart: always
    expose:
      - '86:80'
    environment:
      - VIRTUAL_HOST=la56-b.com
      - LETSENCRYPT_HOST=la56-b.com
      - LETSENCRYPT_EMAIL=blanca@la56-b.com
    volumes:
      - ./Crepas:/usr/share/nginx/html

volumes:
  certs:
  html:
  vhostd:
  confd:
